In [2]:
## Load Libraries
import pandas as pd
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
%matplotlib inline

---

Dot product between two vectors is simply a pairwise-multiplication followed by a summation: for example, $a\cdot b = a_1\times b_2+a_2\times b_2+\cdots+a_n\times b_n.$

---

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

---

$L_2$ norm or the geometric length of a vector denoted as $\lVert a\rVert$ tells us how long a vector is. In 2-dimensions, $\lVert a\rVert_2 = \sqrt{a_1^2+a_2^2}$ and in $n$-dimensions, $\lVert a\rVert_2 = \sqrt{a_1^2+a_2^2+\cdots+a_n^2}.$

---

In [ ]:
np.linalg.norm(a)

---

Cauchy-Schwarz inequality $-1\leq\frac{a\cdot b}{\lVert a\rVert\lVert b\rVert}\leq1.$

---

In [ ]:
np.dot(a, b) / (np.linalg.norm(a)*np.linalg.norm(b))

---

Matrix-vector product is simply a sequence of dot products of the rows of matrix (seen as vectors) with the vector

---

In [9]:
A = np.array([[1,2,-1,-1], [2,4,-2,3], [-1,1,-2,4]])
x = np.array([-1, 1, 1, 0])
print(A)
print(A.shape)
print(A[0])
print(A[1])
print(A[2])
print(A[0].shape)
print(x)
print(np.dot(A, x))

[[ 1  2 -1 -1]
 [ 2  4 -2  3]
 [-1  1 -2  4]]
(3, 4)
[ 1  2 -1 -1]
[ 2  4 -2  3]
[-1  1 -2  4]
(4,)
[-1  1  1  0]
[0 0 0]


---

Linear combination of columns of the matrix using the components of the vector is equivalent to the dot product of the rows of the matrix with the vector

----

In [6]:
print(A)
print(x)
# Dot product of rows of A with x
print(np.dot(A, x))
# Linear combination of columns of A using components of x
print(x[0]*A[:, 0] + x[1]*A[:, 1] + x[2]*A[:, 2] + x[3]*A[:, 3])
np.sum(x[range(4)] * A[:, range(4)], axis = 1) # faster

[[ 1  2 -1 -1]
 [ 2  4 -2  3]
 [-1  1 -2  4]]
[-1  1  1  0]
[0 0 0]
[0 0 0]


array([0, 0, 0])

---

Matrix-matrix product is simply a sequence of matrix-vector products along the last dimension of the second matrix.

---

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 10], [8, 11], [9, 12]])
print(A.shape)
print(A)
print(B.shape)
print(B)
print(np.dot(A, B).shape)
print(np.dot(A, B))

(2, 3)
[[1 2 3]
 [4 5 6]]
(3, 2)
[[ 7 10]
 [ 8 11]
 [ 9 12]]
(2, 2)
[[ 50  68]
 [122 167]]


---

A tensor of dimension 3 corresponding to 4 time stamps, 3 samples, 2 features (HR and BP)

---

In [ ]:
# Create a tensor of dimesion 3
# 4 time stamps, 3 samples, 2 features
# Ordering of the axes: (timestamps, patients, features)
T = np.array([[[74, 128], [79, 116], [71, 116]],
              [[78, 118], [82, 124], [72, 128]],
              [[84, 138], [84, 130], [74, 120]],
              [[82, 126], [76, 156], [82, 132]]])
print(T.shape)
print(T)
print(T[0])
print(T[0][0])

(4, 3, 2)
[[[ 74 128]
  [ 79 116]
  [ 71 116]]

 [[ 78 118]
  [ 82 124]
  [ 72 128]]

 [[ 84 138]
  [ 84 130]
  [ 74 120]]

 [[ 82 126]
  [ 76 156]
  [ 82 132]]]
[[ 74 128]
 [ 79 116]
 [ 71 116]]
[ 74 128]


---

Reshape tensor from axes alignment (timestamps, patients, features) to  the new axes alignment (patients, features, timestamps). That is, the timestamp becomes the last index.

---

In [ ]:
T_reshaped = T.transpose(1, 2, 0)
print(T_reshaped)
print(T_reshaped[0])
print(T_reshaped[:, :, 1])

In [ ]:
T_reshaped = T.transpose(2, 0, 1)
print(T_reshaped)
print(T_reshaped[0])
print(T_reshaped[:, 2, :])

---

Tensor-vector product is simply a sequence of matrix-vector products which in turn are a sequence of dot products of vectors

---

In [ ]:
x = np.array([1, 0])
print(T)
print(x)
print(T.shape)
print(x.shape)
print(np.dot(T, x))
print(np.dot(T, x).shape)

[[[ 74 128]
  [ 79 116]
  [ 71 116]]

 [[ 78 118]
  [ 82 124]
  [ 72 128]]

 [[ 84 138]
  [ 84 130]
  [ 74 120]]

 [[ 82 126]
  [ 76 156]
  [ 82 132]]]
[1 0]
(4, 3, 2)
(2,)
[[74 79 71]
 [78 82 72]
 [84 84 74]
 [82 76 82]]
(4, 3)


---

Tensor-matrix product is simply a sequence of tensor-vector products along the last dimension of the matrix.

---

In [ ]:
# 4 time stamps, 3 samples, 2 features
# Ordering of the axes: (timestamps, patients, features)
T = np.array([[[74, 128], [79, 116], [71, 116]],
              [[78, 118], [82, 124], [72, 128]],
              [[84, 138], [84, 130], [74, 120]],
              [[82, 126], [76, 156], [82, 132]]])
X = np.array([[0, 1], [1, 1]])
print(T.shape)
print(X.shape)
print(np.dot(T, X))
print(np.dot(T, X).shape)

(4, 3, 2)
(2, 2)
[[[128 202]
  [116 195]
  [116 187]]

 [[118 196]
  [124 206]
  [128 200]]

 [[138 222]
  [130 214]
  [120 194]]

 [[126 208]
  [156 232]
  [132 214]]]
(4, 3, 2)


---

Tensor-Tensor product is simply a sequence of tensor-matrix products along the *second-to-last* dimension of the second tensor.

---

In [ ]:
print(T.shape)
S = T.transpose(2, 1, 0)
print(S.shape)
print(np.dot(T, S))



---


The $\texttt{sympy}$ library in Python is for symbolic computing. When using this library, everything including numbers are treated as symbols. This library can be used for calculating the RREF of an augmented matrix coming from a system of linear equations. Consider the system of linear equations $$\boxed{\begin{align*}x_1+2x_2-x_3-x_4&={\color{cyan}1},\\2x_1+4x_2-2x_3+3x_4&={\color{cyan}3},\\-x_1+x_2-2x_3+4x_4&={\color{cyan}2}.\end{align*}}$$
Note the folowing equivalent ways of interpreting this system of equations:
$$\boxed{\begin{align*}\underbrace{\begin{bmatrix}
1 &2 & -1 & -1  \\
2 & 4 & -2 & 3  \\
-1 & 1 & -2 & 4   
\end{bmatrix}}_{A}\underbrace{\begin{bmatrix}x_1\\x_2\\x_3\\x_4\end{bmatrix}}_{x}&=\underbrace{\begin{bmatrix}{\color{cyan}1}\\{\color{cyan}3}\\{\color{cyan}2}\end{bmatrix}}_{\color{cyan}b}\end{align*}}\Longleftrightarrow \underbrace{\boxed{x_1a_1+x_2a_2+x_3a_3+x_4a_4 = {\color{cyan}b}}}_{\color{green}{\text{linear combination of columns of }A}}\Longleftrightarrow \underbrace{\boxed{\begin{bmatrix}a^{(1)}\cdot x\\a^{(2)}\cdot x\\a^{(3)}\cdot x\end{bmatrix} =\begin{bmatrix}{\color{cyan}1}\\{\color{cyan}3}\\{\color{cyan}2}\end{bmatrix}}.}_{\color{green}{\text{Dot product of }x\text{ with rows of }A}}$$ The augmented matrix for this system of equations is $$\begin{align*}
\begin{bmatrix}
1 &2 & -1 & -1 &\lvert& {\color{cyan}1}\\
2 & 4 & -2 & 3 & \lvert&{\color{cyan}3}\\
-1 & 1 & -2 & 4 & \lvert&{\color{cyan}2}
\end{bmatrix}.
\end{align*}$$
The RREF of this augmented matrix can be calculated using the following Python code:

---

In [13]:
# Augmented matrix
Ag = sp.Matrix([[1,2,-1,-1,1], [2,4,-2,3,3], [-1,1,-2,4,2]])

# Return the RREF and the pivot column indices as a tuple
print(Ag.rref())

(Matrix([
[1, 0,  1, 0, -2/5],
[0, 1, -1, 0,  4/5],
[0, 0,  0, 1,  1/5]]), (0, 1, 3))


---

This shows that $x_1, x_2,$ and $x_4$ are pivot variables and that $x_3$ is the only free variable. This system is $\color{green}{consistent}$ with $\color{green}{infinitely\ many\ solutions}$ as we see from the RREF above that
$$x_1=-x_3-(2/5),\,x_2=x_3+(4/5),\,x_4=1/5,$$
where $x_3$ can be any (real) number. We can also express the solution in vector notation as follows:
\begin{align*}
x &= \begin{bmatrix}x_1\\x_2\\x_3\\x_4\end{bmatrix} = \begin{bmatrix}-x_3-\frac{2}{5}\\x_3+\frac{4}{5}\\x_3\\\frac{1}{5}\end{bmatrix} = \underbrace{x_3\begin{bmatrix}-1\\1\\1\\0\end{bmatrix}}_{\text{solution to }Ax=0}+\underbrace{\begin{bmatrix}-\frac{2}{5}\\\frac{4}{5}\\0\\\frac{1}{5}\end{bmatrix}}_{\text{particular solution}},
\end{align*}  
noting again that $x_3$ can be any (real) number. Note that the solution has two parts:

* the first one involving the free variable(s) is the solutions to $Ax = 0$ (called the null space solution);
* the next one is the particular solution to $Ax=b.$




---

In [16]:
np.dot(x,[-1,1,1,0])

3

In [18]:
np.dot(A,[-2/5,4/5,0,1/5])

array([1., 3., 2.])

In [9]:
A1 = np.array([[1,8,3], [-1,-6,-7], [1,2,15], [-1,-4,-11]])  
x1 = np.array([3, 2, 0, 1]) 
A1 = A1.T
print(np.dot(A1, x1))
print("Linear combination of columns of A using components of x: ", x1[0]*A1[:, 0] + x1[1]*A1[:, 1] + x1[2]*A1[:, 2] + x1[3]*A1[:, 3])
print("Better way = ", np.sum(x1[range(4)] * A1[:, range(4)], axis = 1))

Ag1 = sp.Matrix([[1,8,3], [-1,-6,-7], [1,2,15], [-1,-4,-11]])
print(Ag1.rref())

[  0   8 -16]
Linear combination of columns of A using components of x:  [  0   8 -16]
Better way =  [  0   8 -16]
(Matrix([
[1, 0, 19],
[0, 1, -2],
[0, 0,  0],
[0, 0,  0]]), (0, 1))


In [4]:
A2 = np.array([[1,8,3], [-1,-6,-7], [1,2,15], [-1,-4,-11]])  
x2 = np.array([-3, 2, 0, 1]) 
A2 = A2.T

print(np.dot(A2, x2))
print("Linear combination of columns of A using components of x: ", x2[0]*A2[:, 0] + x2[1]*A2[:, 1] + x2[2]*A2[:, 2] + x2[3]*A2[:, 3])
print("Faster way = ", np.sum(x2[range(4)] * A2[:, range(4)], axis = 1)) 

Ag2 = sp.Matrix([[1,8,3], [-1,-6,-7], [1,2,15], [-1,-4,-11]])
print(Ag2.rref())

[ -6 -40 -34]
Linear combination of columns of A using components of x:  [ -6 -40 -34]
Faster way =  [ -6 -40 -34]
RREF and the pivot column indices: 
 (Matrix([
[1, 0, 19],
[0, 1, -2],
[0, 0,  0],
[0, 0,  0]]), (0, 1))


In [5]:
A3 = np.array([[3,2], [1,-1], [4,0], [2,1]])  
x3 = np.array([2,-1,1,1]) 
A3 = A3.T

print(np.dot(A3, x3))
print("Linear combination of columns of A using components of x: ", x3[0]*A3[:, 0] + x3[1]*A3[:, 1] + x3[2]*A3[:, 2] + x3[3]*A3[:, 3])
print("Faster way = ", np.sum(x3[range(4)] * A3[:, range(4)], axis = 1)) 

Ag3 = sp.Matrix([[3,2], [1,-1], [4,0], [2,1]])
print(Ag3.rref())

[11  6]
Linear combination of columns of A using components of x:  [11  6]
Faster way =  [11  6]
RREF and the pivot column indices: 
 (Matrix([
[1, 0],
[0, 1],
[0, 0],
[0, 0]]), (0, 1))


In [8]:
A4 = np.array([[3,2], [1,-1], [4,0], [2,1]])  
x4 = np.array([2,-1,0,1]) 
A4 = A4.T

print(np.dot(A4, x4))
print("Linear combination of columns of A using components of x: ", x4[0]*A4[:, 0] + x4[1]*A4[:, 1] + x4[2]*A4[:, 2] + x4[3]*A4[:, 3])
print("Faster way = ", np.sum(x4[range(4)] * A4[:, range(4)], axis = 1)) 

Ag4 = sp.Matrix([[3,2], [1,-1], [4,0], [2,1]])
print(Ag4.rref())

[7 6]
Linear combination of columns of A using components of x:  [7 6]
Faster way =  [7 6]
RREF and the pivot column indices: 
 (Matrix([
[1, 0],
[0, 1],
[0, 0],
[0, 0]]), (0, 1))


In [7]:

A5 = np.array([[1,-2,0,2], [1,1,3,-1]])  
x5 = np.array([1,2])
A5 = A5.T

print(np.dot(A5, x5))
print("Linear combination of columns of A using components of x: ", x5[0]*A5[:, 0] + x5[1]*A5[:, 1])
print("Faster way = ", np.sum(x5[range(2)] * A5[:, range(2)], axis = 1)) # faster

Ag = sp.Matrix([[1,8,3], [-1,-6,-7], [1,2,15], [-1,-4,-11]])
Ag = Ag.T
print(Ag.rref())

[3 0 6 0]
Linear combination of columns of A using components of x:  [3 0 6 0]
Faster way =  [3 0 6 0]
RREF and the pivot column indices: 
 (Matrix([
[1, 0, -2, 1],
[0, 1, -3, 2],
[0, 0,  0, 0]]), (0, 1))
